# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy a Node.js app and an Angular app to an Azure

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install Nx CLI
        run: npm install -g nx

      - name: npm install, build, and test
        run: |
          npm install
          nx build frontend
          nx build data-api
          nx build rcmnd-api

      - name: Zip artifacts for deployment
        run: |
          echo ${GITHUB_WORKSPACE}
          zip data-api-release.zip ./* -r
          cd ${GITHUB_WORKSPACE}/dist/apps/frontend/ && zip ${GITHUB_WORKSPACE}/frontend-release.zip ./* -r

      - name: Upload frontend artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: frontend
          path: frontend-release.zip
          
      - name: Upload data-api artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: data-api
          path: data-api-release.zip
          
          
  deploy-frontend:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: frontend

      - name: Unzip artifact for deployment
        run: unzip frontend-release.zip
        
      - name: Deploy to static azure web app
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.ANGULAR_PUBLISHTOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          app_location: "/" # App source code path
          api_location: "" # Api source code path - optional
          output_location: "" # Built app content directory - optional


  deploy-data-api:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: data-api

      - name: Unzip artifact for deployment
        run: unzip data-api-release.zip
       
      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'pokemon-cswf'
          slot-name: 'Production'
          publish-profile: ${{ secrets.NEXTJS_PUBLISHPROFILE }}
          package: .
